# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  environment.etc."machine-id".source = "/nix/persistent/etc/machine-id";
  environment.etc."NetworkManager/system-connections".source = "/nix/persistent/etc/NetworkManager/system-connections";

  fileSystems."/etc/nixos" = {
    device = "/nix/persistent/etc/nixos";
    fsType = "none";
    options = [ "bind" ];
  };

  #fileSystems."/home/sth" = {
  #  device = "/nix/persistent/home/sth";
  #  fsType = "none";
  #  options = [ "bind" ];
  #};

  fileSystems."/root" = {
    device = "/nix/persistent/home/root";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/var/lib/boltd" = {
    device = "/nix/persistent/var/lib/boltd";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/var/log" = {
    device = "/nix/persistent/var/log";
    fsType = "none";
    options = [ "bind" ];
  };
}
